export type Named={_id:string;name:string;color?:string};export type User=Named&{email:string;avatar?:string;role:{name:string;permissions:string[]}};export type Metadata={stages:(Named&{sequence:number;probability:number;folded:boolean;isWon:boolean})[];users:User[];teams:Named[];tags:Named[];sources:Named[];campaigns:Named[];mediums:Named[];lostReasons:Named[]};export type Opportunity={_id:string;title:string;company?:Named;contact?:Named;email?:string;phone?:string;expectedRevenue:number;recurringRevenue:number;probability:number;priority:number;salesperson?:User;salesTeam?:Named;stage:Named;tags:Named[];source?:Named;campaign?:Named;medium?:Named;expectedClosingDate?:string;status:'open'|'won'|'lost';kanbanOrder:number;internalNotes?:string;timeline?:Timeline[];activities?:Activity[]};export type Lead={_id:string;title:string;contactName?:string;companyName?:string;email?:string;phone?:string;expectedRevenue:number;priority:number;salesperson?:User;salesTeam?:Named;source?:Named;campaign?:Named;tags:Named[];status:string;converted:boolean;convertedOpportunity?:{_id:string;stage?:Named};createdAt:string};export type Activity={_id:string;summary:string;dueDate:string;status:string;activityType:Named;assignedTo:User;relatedModel:string;relatedId:string};export type Timeline={_id:string;eventType:string;message:string;createdAt:string;createdBy:User};export type Paged<T>={data:T[];pagination:{page:number;limit:number;total:number;pages:number}};

// --- WhatsApp AI Sales Agent -------------------------------------------------
export type WALead=Named&{title:string;contactName?:string;companyName?:string;email?:string;phone?:string;expectedRevenue:number;priority:number;salesperson?:User;leadScore:number;leadTemperature:'Cold'|'Warm'|'Hot'|'Very Hot';qualificationStatus:string;customerIntent?:string;budget?:string;purchaseTimeline?:string;quantity?:string;requirements:string[];painPoints:string[];objections:string[];productInterest:string[];aiSummary?:string;recommendedNextAction?:string;salesProbability?:number;lastAiAnalysisAt?:string;status:string;converted:boolean;convertedOpportunity?:{_id:string;stage?:Named};tags:Named[];source?:Named;createdAt:string};
export type ControlStatus='AI_ACTIVE'|'WAITING_HUMAN'|'HUMAN_ACTIVE'|'AI_PAUSED';
export type WAConversation={_id:string;contact?:{_id:string;name:string;email?:string};lead?:WALead;phoneNumber:string;customerName?:string;assignedTo?:User;status:'open'|'pending'|'resolved'|'archived';controlStatus:ControlStatus;aiEnabled:boolean;humanTakeover:boolean;aiMessageCount:number;language:'en'|'hi'|'hinglish';lastMessage?:string;lastMessageAt?:string;unreadCount:number;sentiment?:'positive'|'neutral'|'negative';sentimentConfidence?:number;detectedIntent?:string;tags:Named[];archived:boolean;createdAt:string};
export type WAMessage={_id:string;conversation:string;whatsappMessageId?:string;direction:'INBOUND'|'OUTBOUND';type:string;text?:string;mediaUrl?:string;mediaMimeType?:string;caption?:string;filename?:string;location?:{lat:number;lng:number;name?:string;address?:string};templateName?:string;timestamp:string;status:'QUEUED'|'SENT'|'DELIVERED'|'READ'|'FAILED';failReason?:string;aiGenerated:boolean;sentBy?:User;deletedAt?:string;deletedBy?:User|string;intent?:string;sentiment?:string};
export type AIConfig={_id:string;agentTemplateVersion?:number;agentName:string;agentRole:string;companyName:string;companyDescription?:string;welcomeMessage:string;tone:'Professional'|'Friendly'|'Casual'|'Sales-focused'|'Custom';customTone?:string;language:'en'|'hi'|'hinglish'|'auto';qualificationQuestions:string[];businessHours?:{timezone:string;days:{day:number;start?:string;end?:string;enabled?:boolean}[]};outsideHoursMessage:string;welcomeMenuEnabled:boolean;humanHandoffButtonEnabled:boolean;menuButtonLabels?:{question?:string;pricing?:string;human?:string;ai?:string};humanRequestedMessage:string;aiResumedMessage:string;autoGreetNewLeads:boolean;autoGreetTemplate?:string;sendServiceListOnReply:boolean;serviceListIntro:string;provider:'anthropic'|'openai'|'openrouter'|'mock';aiModel?:string;creativity:number;maxResponseLength:number;maxAiMessagesBeforeEscalation:number;globalAiEnabled:boolean;escalationRules:{onHumanRequest:boolean;onNegativeSentiment:boolean;onLowConfidence:boolean;onComplexPricing:boolean;onSeriousComplaint:boolean;onVipLead:boolean;vipLeadScoreThreshold:number;lowConfidenceThreshold:number}};
export type KBProduct={_id:string;name:string;description?:string;category?:string;price?:number;currency?:string;priceType:'fixed'|'starting_at'|'custom';sku?:string;link?:string;active:boolean};
export type KBService=KBProduct&{duration?:string;deliverables?:string[]};
export type KBFaq={_id:string;question:string;answer:string;category?:string;active:boolean};
export type KBArticle={_id:string;title:string;content:string;category:string;active:boolean};
export type WATemplate={_id:string;templateName:string;category:'MARKETING'|'UTILITY'|'AUTHENTICATION';language:string;header?:string;body:string;footer?:string;status:'PENDING'|'APPROVED'|'REJECTED'};
export type WACampaign={_id:string;campaignName:string;template?:WATemplate;audience:Record<string,unknown>;scheduledAt?:string;status:'draft'|'scheduled'|'sending'|'completed'|'failed'|'cancelled';audienceSize:number;sent:number;delivered:number;read:number;failed:number;replied:number;createdAt:string};
export type WhatsAppAccountRow={_id:string;label:string;phoneNumberId:string;businessAccountId:string;displayPhoneNumber?:string;active:boolean};
export type WADashboardMetrics={newWhatsAppLeads:number;activeConversations:number;aiConversations:number;humanConversations:number;hotLeads:number;humanHandoffs:number;messagesToday:number;whatsappConversionRate:number;messagesByDay:{_id:string;count:number}[];leadTemperature:{_id:string;count:number}[]};
