import type { Request, Response } from 'express';
import mongoose from 'mongoose';
import { Activity, ActivityType, Campaign, Company, Contact, Lead, LeadSource, LostReason, Medium, Notification, Opportunity, PipelineStage, SalesTeam, SavedFilter, Tag, TimelineEvent, User } from '../models/index.js';
import { accessScope } from '../middleware/auth.js';
import { leadInput, listQuery, opportunityInput } from '../validators/index.js';
import { ApiError, escapeRegex } from '../utils/http.js';
import { convertLead, moveOpportunity } from '../services/crm.service.js';
import { ensureWorkspaceDefaults } from '../utils/bootstrap.js';
import { greetNewLead } from '../services/greeting.service.js';

const pop = [{ path: 'salesperson', select: 'name email avatar' }, { path: 'salesTeam', select: 'name' }, { path: 'stage', select: 'name color sequence probability' }, { path: 'company', select: 'name' }, { path: 'contact', select: 'name' }, { path: 'tags', select: 'name color' }, { path: 'source', select: 'name' }, { path: 'campaign', select: 'name' }];
const leadPop = [{ path: 'salesperson', select: 'name email avatar' }, { path: 'salesTeam', select: 'name' }, { path: 'tags', select: 'name color' }, { path: 'source', select: 'name' }, { path: 'medium', select: 'name' }, { path: 'campaign', select: 'name' }, { path: 'convertedOpportunity', select: 'stage', populate: { path: 'stage', select: 'name color sequence' } }];
export async function listOpportunities(req: Request, res: Response) {
  const q = listQuery.parse(req.query); const filter: any = { ...accessScope(req) };
  for (const key of ['status','stage','salesperson','source','campaign'] as const) if (q[key]) filter[key] = q[key];
  if (q.team) filter.salesTeam = q.team; if (q.priority !== undefined) filter.priority = q.priority;
  if (q.search) filter.$or = ['title','email','phone'].map((key) => ({ [key]: new RegExp(escapeRegex(q.search!), 'i') }));
  const skip = (q.page - 1) * q.limit;
  const [data, total] = await Promise.all([Opportunity.find(filter).populate(pop).sort({ [q.sortBy]: q.sortOrder === 'asc' ? 1 : -1 }).skip(skip).limit(q.limit).lean(), Opportunity.countDocuments(filter)]);
  res.json({ data, pagination: { page: q.page, limit: q.limit, total, pages: Math.ceil(total / q.limit) } });
}
export async function createOpportunity(req: Request, res: Response) { const input = opportunityInput.parse(req.body); const count = await Opportunity.countDocuments({ stage: input.stage }); const doc = await Opportunity.create({ ...input, kanbanOrder: count, createdBy: req.user!._id, updatedBy: req.user!._id }); await TimelineEvent.create({ createdBy: req.user!._id, relatedModel: 'Opportunity', relatedId: doc._id, eventType: 'opportunity_created', message: 'Opportunity created' }); res.status(201).json(await doc.populate(pop)); }
export async function getOpportunity(req: Request, res: Response) { const doc = await Opportunity.findOne({ _id: req.params.id, ...accessScope(req) }).populate(pop); if (!doc) throw new ApiError(404, 'Opportunity not found'); const [timeline, activities] = await Promise.all([TimelineEvent.find({ relatedModel: 'Opportunity', relatedId: doc._id }).populate('createdBy','name avatar').sort('-createdAt'), Activity.find({ relatedModel: 'Opportunity', relatedId: doc._id }).populate('assignedTo activityType').sort('dueDate')]); res.json({ ...doc.toObject(), timeline, activities }); }
export async function updateOpportunity(req: Request, res: Response) { const input = opportunityInput.partial().parse(req.body); const doc = await Opportunity.findOneAndUpdate({ _id: req.params.id, ...accessScope(req) }, { ...input, updatedBy: req.user!._id }, { new: true, runValidators: true }).populate(pop); if (!doc) throw new ApiError(404,'Opportunity not found'); res.json(doc); }
export async function setOutcome(req: Request, res: Response) { const status = req.body.status as string; if (!['won','lost','open'].includes(status)) throw new ApiError(422,'Invalid status'); const update: any = { status, updatedBy: req.user!._id, wonAt: status === 'won' ? new Date() : undefined, lostAt: status === 'lost' ? new Date() : undefined, lostReason: status === 'lost' ? req.body.lostReason : undefined, lostNotes: status === 'lost' ? req.body.lostNotes : undefined }; const doc = await Opportunity.findOneAndUpdate({ _id: req.params.id, ...accessScope(req) }, update, { new: true }).populate(pop); if (!doc) throw new ApiError(404,'Opportunity not found'); await TimelineEvent.create({ createdBy: req.user!._id, relatedModel:'Opportunity', relatedId: doc._id, eventType:`opportunity_${status === 'open' ? 'reopened' : status}`, message: status === 'open' ? 'Opportunity reopened' : `Opportunity marked ${status}` }); res.json(doc); }
export async function move(req: Request, res: Response) { const body = req.body as { stageId: string; orderedIds: string[] }; if (!mongoose.isValidObjectId(body.stageId) || !Array.isArray(body.orderedIds) || body.orderedIds.some(x => !mongoose.isValidObjectId(x))) throw new ApiError(422,'Invalid move'); await moveOpportunity(String(req.params.id), body.stageId, body.orderedIds, req.user!._id); res.json({ success: true }); }

export async function deleteOpportunity(req: Request, res: Response) { const doc = await Opportunity.findOneAndDelete({ _id: req.params.id, ...accessScope(req) }); if (!doc) throw new ApiError(404, 'Opportunity not found'); await Promise.all([TimelineEvent.deleteMany({ relatedModel: 'Opportunity', relatedId: doc._id }), Activity.deleteMany({ relatedModel: 'Opportunity', relatedId: doc._id }), Lead.updateMany({ convertedOpportunity: doc._id }, { $unset: { convertedOpportunity: 1 } })]); res.status(204).end(); }

export async function listLeads(req: Request, res: Response) { const q = listQuery.parse(req.query); const filter:any = { ...accessScope(req) }; for (const key of ['status','salesperson','source','campaign'] as const) if (q[key]) filter[key] = q[key]; if (q.team) filter.salesTeam = q.team; if (q.priority !== undefined) filter.priority = q.priority; if(q.search) filter.$or=['title','contactName','companyName','email','phone'].map(k=>({[k]:new RegExp(escapeRegex(q.search!),'i')})); const [data,total]=await Promise.all([Lead.find(filter).populate(leadPop).sort({[q.sortBy]:q.sortOrder==='asc'?1:-1}).skip((q.page-1)*q.limit).limit(q.limit).lean(),Lead.countDocuments(filter)]); res.json({data,pagination:{page:q.page,limit:q.limit,total,pages:Math.ceil(total/q.limit)}}); }
export async function createLead(req:Request,res:Response){const input=leadInput.parse(req.body);const doc=await Lead.create({...input,createdBy:req.user!._id,updatedBy:req.user!._id});
  // Fire-and-forget: a WhatsApp/template failure must never fail the lead creation itself.
  void greetNewLead(doc._id,req.user!._id).catch(error=>console.error('[lead] auto-greet failed',error));
  res.status(201).json(doc);}
export async function updateLead(req:Request,res:Response){const input=leadInput.partial().parse(req.body);if(input.status){const current=await Lead.findOne({_id:req.params.id,...accessScope(req)}).select('converted');if(current?.converted)throw new ApiError(409,'A converted lead cannot change status');}const doc=await Lead.findOneAndUpdate({_id:req.params.id,...accessScope(req)},{...input,updatedBy:req.user!._id},{new:true,runValidators:true});if(!doc)throw new ApiError(404,'Lead not found');res.json(doc);}
export async function deleteLead(req:Request,res:Response){const doc=await Lead.findOneAndDelete({_id:req.params.id,...accessScope(req)});if(!doc)throw new ApiError(404,'Lead not found');res.status(204).end();}
export async function convert(req:Request,res:Response){res.status(201).json(await convertLead(String(req.params.id),req.user!._id));}

export async function dashboard(_req:Request,res:Response){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const [summary,pipeline,monthly,activities]=await Promise.all([Opportunity.aggregate([{$group:{_id:null,total:{$sum:1},expectedRevenue:{$sum:'$expectedRevenue'},wonRevenue:{$sum:{$cond:[{$eq:['$status','won']},'$expectedRevenue',0]}},won:{$sum:{$cond:[{$eq:['$status','won']},1,0]}},lost:{$sum:{$cond:[{$eq:['$status','lost']},1,0]}}}}]),Opportunity.aggregate([{$match:{status:'open'}},{$lookup:{from:'pipelinestages',localField:'stage',foreignField:'_id',as:'stage'}},{$unwind:'$stage'},{$group:{_id:'$stage.name',value:{$sum:'$expectedRevenue'},count:{$sum:1},sequence:{$first:'$stage.sequence'}}},{$sort:{sequence:1}}]),Opportunity.aggregate([{$match:{status:'won',wonAt:{$ne:null}}},{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$wonAt'}},value:{$sum:'$expectedRevenue'}}},{$sort:{_id:1}},{$limit:12}]),Activity.aggregate([{$match:{status:'planned'}},{$facet:{today:[{$match:{dueDate:{$gte:today,$lt:tomorrow}}},{$count:'count'}],overdue:[{$match:{dueDate:{$lt:today}}},{$count:'count'}]}}])]);const s=summary[0]??{total:0,expectedRevenue:0,wonRevenue:0,won:0,lost:0};res.json({summary:{...s,conversionRate:s.won+s.lost?Math.round(s.won/(s.won+s.lost)*100):0,activitiesToday:activities[0]?.today[0]?.count??0,activitiesOverdue:activities[0]?.overdue[0]?.count??0},pipeline,monthly});}
export async function report(req:Request,res:Response){const dimension=String(req.query.dimension??'stage');const measure=String(req.query.measure??'expectedRevenue');const allowed:any={stage:'stage',salesperson:'salesperson',salesTeam:'salesTeam',source:'source',campaign:'campaign',month:{$dateToString:{format:'%Y-%m',date:'$createdAt'}},lostReason:'lostReason'};if(!allowed[dimension])throw new ApiError(422,'Invalid dimension');const sum=measure==='count'?{$sum:1}:{$sum:measure==='proratedRevenue'?{$multiply:['$expectedRevenue',{$divide:['$probability',100]}]}:`$${['expectedRevenue','probability'].includes(measure)?measure:'expectedRevenue'}`};res.json(await Opportunity.aggregate([{$match:{}},{$group:{_id:allowed[dimension],value:sum,count:{$sum:1}}},{$sort:{value:-1}},{$limit:50}]));}

export async function metadata(_req:Request,res:Response){await ensureWorkspaceDefaults();const [stages,users,teams,tags,sources,campaigns,mediums,lostReasons,activityTypes]=await Promise.all([PipelineStage.find({active:true}).sort('sequence').lean(),User.find({active:true,deletedAt:{$exists:false}}).select('name email avatar').sort('name').lean(),SalesTeam.find({active:true}).lean(),Tag.find({active:true}).lean(),LeadSource.find({active:true}).lean(),Campaign.find({active:true}).lean(),Medium.find({active:true}).lean(),LostReason.find({active:true}).lean(),ActivityType.find({active:true}).lean()]);res.json({stages,users,teams,tags,sources,campaigns,mediums,lostReasons,activityTypes});}
export async function genericList(model:any,req:Request,res:Response){res.json(await model.find({}).sort('name').limit(500));}
export const models:Record<string,any>={companies:Company,contacts:Contact,teams:SalesTeam,stages:PipelineStage,tags:Tag,sources:LeadSource,campaigns:Campaign,mediums:Medium,lostReasons:LostReason,activityTypes:ActivityType,activities:Activity,filters:SavedFilter,notifications:Notification};
